baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Contracts.ruby"
theme = "blackburn"

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/home/"

  [[menu.main]]
    name = "Quickstart"
    weight = 1
    identifier = "quickstart"
    url = "/quickstart/"

  [[menu.main]]
    name = "Tutorial"
    weight = 2
    identifier = "tutorial"
    url = "/tutorial/"

  [[menu.main]]
    name = "Contributing"
    weight = 3
    identifier = "contributing"
    url = "/contributing/"

  [[menu.main]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/about/"
